### ISSUE TITLE
Non integer steps-per-mm

### ISSUE THREAD

**Issue by Jgr2023** [hobbymachinist/els#8]
First of all, many thanks for all your work on this project!

I'm looking at fitting the ELS to a lathe with a 6mm pitch leadscrew and with a 200 steps/rev stepper on the z-axis.

This gives a non-integer steps-per-mm. 

I trying to understand if this will cause an accumulating error in open loop.

I think I can see a solution by storing two numbers instead of one number (a number of steps and a corresponding mm of travel), but that may be getting a bit ahead of myself.

I look forward to hearing your thoughts.

Thanks,
J.

**Comment by hobbymachinist** [comment]
Thanks. The best option is to add a 1.5x pulley reduction from your stepper to the leadscrew, so you get an even number. 200 steps = 4mm, 50 steps per mm. No need to make the software complicated and as an added benefit you get extra torque.
